package dk.aau.cs.giraf.pictogram;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.media.MediaPlayer.OnCompletionListener;
import android.util.Log;
import android.view.Gravity;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.HashSet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import dk.aau.cs.giraf.oasis.lib.*;
import dk.aau.cs.giraf.oasis.lib.models.*;
//TODO: Make custom ImageView and TextView with predefined "niceness"

/**
 * Extension of {@FrameLayout} used for GIRAF pictograms.
 *
 * For proper Pictogram initialization refere to {@link PictoFactory}.
 *
 * @author Croc
 *
 */
public class Pictogram extends FrameLayout {
    private static final String TAG = "Pictogram";

    /* TODO: add xml from Croc to the application, making it possible for others
       to use a more scalable image.*/

    private final String imagePath;
    private final String textLabel;
    private final String audioPath;
    private final String name;
    private final boolean shareable;
    private final long pictogramID;

    private Gravity textGravity;

    /**
     * Constructor used by {@link PictoFactory} for populating the fields in a
     * Pictogram.
     *
     * <p> The input to this constructor is not verified because it only should
     * be used by a {@link PictoFactory}
     *
     * @deprecated As of next release this method will be protected and not for
     * use outside of pictogram.
     *
     * @param context context in which this pictogram is generated.
     * @param image the path to the image used.
     * @param text the label for the image.
     * @param audio the path to the audio used.
     * @param name name of the pictogram.
     * @param share if this pictogram is public or not.
     * @param id usually an id generated by the database.
     * @return A pictogram for use in GIRAF.
     */
    public Pictogram(Context context, final String image,
                     final String text, final String audio,
                     final String name, final boolean share,
                     final long id) {
        super(context);
        this.imagePath = image;
        this.textLabel = text;
        this.audioPath = audio;
        this.name = name;
        this.shareable = share;
        this.pictogramID = id;
    }

    /**
     * Populates the view with both image and text, making it an actual viewable
     * view.
     */
    public void renderAll() {
        renderImage();
        renderText();
    }

    /**
     * Populates the view with text, making it an actual viewable view.
     * The gravity is by default set to {@value} TODO insert value
     * {@link #renderText(int)} can be used if you want to place the text.
     */
    public void renderText() {
        TextView text = new TextView(getContext());
        text.setText(textLabel);
        text.setGravity(Gravity.CENTER_HORIZONTAL | Gravity.BOTTOM);
        this.addView(text);
    }

    /**
     * Populates the view with text, making it an actual viewable view.
     * @param gravity is the location of the text in the image.
     */
    public void renderText(int gravity) {
        TextView text = new TextView(getContext());
        text.setText(textLabel);
        text.setPadding(10, 10, 10, 10);
        text.setGravity(Gravity.CENTER_HORIZONTAL | gravity);
        this.addView(text);
    }

    /**
     * Populates the view with an image, making it an actual viewable view.
     */
    public void renderImage() {
        Bitmap img = BitmapFactory.decodeFile(imagePath);
        ImageView image = new ImageView(getContext());
        String msg = imagePath + " found, making bitmap.";
        Log.d(TAG, msg);
        image.setImageBitmap(img);
        this.addView(image);
    }

    /**
     * A check if the {@link audioPath} is null.
     */
    public boolean hasAudio() {
        return audioPath != null;
    }

    /**
     * Function used for playing audio and not doing any action when it finishes.
     */
    public void playAudio() {
        playAudio(null);
    }

    /**
     * Play audio using the {@link AudioPlayer} class written by digiPECS in 2011
     * @param listener the callback that will be run
     */
    public void playAudio(final OnCompletionListener listener){
        if(hasAudio()){
            new Thread(new Runnable(){
                    @Override
                                        public void run(){
                        AudioPlayer.INSTANCE.play(audioPath, listener);
                    }
                }).start();

            String msg = "Played audio: " + textLabel;
            Log.d(TAG, msg);
            //TODO check that the thread is stopped again at some point. [OLD PARROT TODO]
        } else {
            Log.d(TAG, "No sound attatched: " + pictogramID + "\n\tOn:" + textLabel);
        }
    }

    /**
     * @return name the name of the pictogram as represented in the database.
     */
    public String getName(){
        return name;
    }

    /**
     * @return shareable if true the pictogram is public and shareable, if false
     * it is not.
     */
    public boolean getShareable(){
        return shareable;
    }

    /**
     * The Oasis database does not allow for easy access to the attatched tags
     * of a certain piece of Media so this method has not been implemented.
     */
    public List<String> getTags() {
        return null;
    }

    /**
     * @return imagePath the path to the image used for the pictogram.
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * @return textLabel the label used for the pictogram.
     */
    public String getTextLabel() {
        return textLabel;
    }

    /**
     * @return audioPath the path to the audio used for the pictogram.
     */
    public String getAudioPath() {
        return audioPath;
    }
    /**
     * @return pictogramID the id which the pictogram is found under in the database.
     */
    public long getPictogramID() {
        return pictogramID;
    }

}
